# use openpyxl to open an excel sheet
# use python classes to sort attributes of the excel sheet


import openpyxl
        

# workbook class with pointer to the workbook
class Workbook():

    # constructor/attribute __init__() that takes a filename
    # and then uses openpyxl to open that file and store the
    # workbook pointer in a local member.  
    def __init__(self, file):
        self.file = file
    
    @property
    def file(self):
        """The file property."""
        print("Get file")
        return self._file

    @file.setter
    def file(self, filename):
        print("Set filename")
        self._file = openpyxl.load_workbook(filename)
    

	# .worksheets returns a list of sheetnames
    @property
    def worksheets(self):
        return self._file.sheetnames

    # attribute/method that returns a list of VirPyTSheet objects
    #@property    
    def sheets(self):
        # constructor should be generated by
        # wrapping individual sheet returned by wb.worksheets
        return [Sheet(temp_sheet) for temp_sheet in self._file]



# sheet class with pointers to sheets in the workbook        
class Sheet():
    def __init__(self, sheet):
        self._sheet = Workbook.worksheets
        
        
#class Table():
#class Row():
#class Cell():

              

if __name__ == '__main__':
    #filename = input(print("Input filename: "))
    
    wb = Workbook('sample.xlsx')
    print(wb.file)		#address of openpyxl workbook object
    
    print(wb.sheets())	# returns list of sheet objects and addresses
    print(wb.worksheets)	#list of names of worksheets
    
    #worksheet = Sheet(workbook.file.active)
    #if worksheet:
    #    print("ok!")

    for sheet in wb.worksheets:		#prints each sheet title
        print("Found sheet named %s" % sheet)

